# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-2026 SEN Labs e.U.

SCHEMA="https://github.com/sen-laboratories/sen-oni/tree/main/schema/sen-books.yaml"
AUTHOR="Gregor B. Rosenauer <gregor.rosenauer@gmail.com>"
VERSION="0.1.0"
DESCRIPTION="This ontology defines entities and relations for working with books."
STABLE=false
